development:
  adapter: postgresql
  encoding: unicode
  database: ShortenedUrl
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: ShortenedUrl
  pool: 5
  username: postgres
  password: postgres