# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc6bd30a1d56818d0317b727d7774314083fcbbc528615572442d2493549f2745deceff9470d6bd52f8acd426a08e67e05899436572dc54492baa26ad78ceb9d

test:
  secret_key_base: 4bfca3818f870fb82fc9f4978439c032bae01e10e0b446ac2927aa05c60e809ff373a479ef0badce25a479e2c1a6caa03e1026acff7a56c64bf794712c1b0a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
